<?php

/**
 * @file
 * A sample module for WU13 training.
 *
 * This module exposes a block that prints important
 * system information for the user. It also exposes and
 * administration area that allows the user to enter these
 * messages.
 */

/**
 * Implements hook_menu().
 */
function system_status_menu() {
  $items = array();

  $items['admin/config/system/system_status'] = array(
    'title' => 'System status',
    'description' => 'Set the system status, which can displayed as a block through the block system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('system_status_form'),
    'access arguments' => array('set syatem status'),
  );

  return $items;
}

/**
 * Display the form that enables users to enter the current system status.
 */
function system_status_form($form, &$form_state) {
  $form['system_status'] = array(
    '#type' => 'textfield',
    '#title' => t('Status'),
    '#description' => t('The current system status.'),
    '#default_value' => variable_get('system_status', ''),
    '#size' => 40,
    '#maxlength' => 255,
  );

  return system_settings_form($form);
}

/**
 * Submit callback when a system status is being set.
 *
 * @see system_status:submit_form()
 */
function system_status_form_submit($form, &$form_state) {
  variable_set('system_status', $form_state['values']['system_status']);
}

/**
 * Validate callback when a system status is being set..
 *
 * @see system_status:submit_form()
 */
function system_status_form_validate($form, &$form_state) {
  if (empty($form_state['values']['system_status'])) {
    form_set_error('System Status', 'You must enter a system status.');
  }
}

/**
 * Implements hook_help().
 */
function system_status_help($path, $arg) {
  if ($path == 'admin/help#system_status') {
    return t('A sample module that displays a text message for WU13 training.');
  }
}

/**
 * Implements hook_block_info().
 */
function system_status_block_info() {
  $blocks = array();
  
  $blocks['system_status'] = array(
    'info' => t('The current system status'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function system_status_block_view($block_name = '') {
  if ($block_name == 'system_status') {
    $block = array(
      'subject' => t('System Status'),
      'content' => variable_get('system_status', ''),
    );
    
    return $block;
  }
}
